config/routes.rb
Rails.application.routes.draw do
  #start app with root route
  root 'sessions#new'
  # Create custom routes 
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions/' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  
  resources :users
  
  resources :games do
    resources :subscriptions
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :subscriptions
    has_many :users, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :user
    belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
    has_many :subscriptions
    has_many :games, through: :subscriptions
    validates :user_name, :first_name, :last_name, :email, :password, presence: true
    validates :user_name, :email, uniqueness: true
    has_secure_password

    def self.find_or_create_by_omniauth(auth_hash) 
        self.where(:email => auth_hash['info']['email']).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def new
        @game = Game.new
    end

    def show
        @game = Game.find(params[:id])
    end

    def create
        @game = Game.new(game_params)
        
        if @game.save

        else
            render :new
        end
    end

    def edit
        @game = Game.find(params[:id])
    end

    def update
        @game = Game.find(params[:id])

        if @game.update(game_params)
        
        else
            render :edit
        end
    end

    def destroy
        @game = Game.find(params[:id])
        @game.destroy
    end

    private

    def game_params
        params.require(:game).permit(:title, :platform)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :verify_authenticity_token

    def new
        @user = User.new
    end

    def create
        if auth_hash = request.env['omniauth.auth']
            @user = User.find_or_create_by_omniauth(auth_hash)
            session[:user_id] = @user.id
            redirect_to user_path
        else
            @user = User.find_by(email: params[:email])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                redirect_to login_path 
            end
        end
    end

    def destroy
        session.clear
        redirect_to login_path
    end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

    def new
        @subscription = Subscription.new(user_id: params[:user_id])
    end

    def show
        @subscription = Subscription.find(params[:id])
    end

    def create
        @subscription = Subscription.new(subscription_params)

        if @subscription.save

        else
            render :new
        end
    end

    def edit
        @subscription = Subscription.find(params[:id])
    end

    def update
        
    end

    def destroy
        @subscription = Subscription.find(params[:id])
        @subscription.destroy
        redirect_to user_path(@user)
    end

    private

    def subscription_params
        params.require(:subscription).permit(:term, :user_id, :game_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :verify_authenticity_token


    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_url
    end

    private

    def user_params
        params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamesub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_tag @user, method: 'patch' do %>
    <% if @user.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @user.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
        <%= form_for @user, url:'/signup' do |f| %>
            <%= f.label :user_name %>
            <%= f.text_field :user_name %><br><br>

            <%= f.label :first_name %>
            <%= f.text_field :first_name %><br><br>

            <%= f.label :last_name %>
            <%= f.text_field :last_name %><br><br>

            <%= f.label :email %>
            <%= f.email_field :email %><br><br>

            <%= f.label :password %>
            <%= f.password_field :password %><br><br>
            <%= f.submit "edit user" %>    
        <% end %>
    </div>        
<% end %>

app/views/users/new.html.erb
<h2>Sign Up Here!</h2>

<%= form_tag @user, method: 'post' do %>
    <% if @user.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @user.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
        <%= form_for @user, url:'/signup' do |f| %>
            <%= f.label :user_name %>
            <%= f.text_field :user_name %><br><br>

            <%= f.label :first_name %>
            <%= f.text_field :first_name %><br><br>

            <%= f.label :last_name %>
            <%= f.text_field :last_name %><br><br>

            <%= f.label :email %>
            <%= f.email_field :email %><br><br>

            <%= f.label :password %>
            <%= f.password_field :password %><br><br>

            <%= f.submit "Sign Up" %>    
        <% end %>
    </div>        
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.first_name %></h1>

<%= link_to 'edit user', edit_user_path(@user) %> |
<%= link_to 'logout', sessions_path, method: 'delete' %>